# -*- coding: utf-8 -*-
"""count11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wit504L0IFUO5kLoIR4d-v4JgTepoEtI
"""

def count11(n):    
  cont = 0
  if len(n)==0:
    return cont
  for i in range(0,len(n)+1):
    if n[i:i+2] == "11" and n[i+1:i+3] != "11":
      cont +=1
  return cont + count11(n[i:i+2])

  
count11("111")