# -*- coding: utf-8 -*-
"""strcount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mx6Tk6tL4w3y_vg5BblZ4i3SOtXBidXu
"""

def strcount(str1,str2):
  cont = 0
  i = 0
  if len(str1)==0:
    return cont
  else:
    if str1[i:i+2] == str2:
        cont +=1 
  return cont + strcount(str1[i+1:],str2)
  



strcount("juhtju","ju")