# -*- coding: utf-8 -*-
"""sumdigits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mx6Tk6tL4w3y_vg5BblZ4i3SOtXBidXu
"""

def sumdigits(n):    
  sum = 0
  if n==0:
    return sum
  else:
    sum+=n%10
  return sum + sumdigits(n/10)


sumdigits(123)