# -*- coding: utf-8 -*-
"""adn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mx6Tk6tL4w3y_vg5BblZ4i3SOtXBidXu
"""

def adn(str1,str2,m,n):
  cont = 0 
  if m == 0 or n ==0:
      return 0
  else:
    if str1[:m]==str2[:n]:
      return 1 + adn(str1[:-1],str2,m-1,n)
  return max(adn(str1[:-1],str2,m-1,n),adn(str1,str2[:-1],m,n-1))


adn("abjk","afgk",4,4)